---
format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios
pipelines:
  deploy_all:
    stages:
    - prepare_stage: {}
    - build_stage: {}
    - notify_stage: {}
stages:
  prepare_stage:
    workflows:
    - prepare: {}
  build_stage:
    workflows:
    - build_iOS_16: {}
    - build_iOS_pre_16: {}
  notify_stage:
    workflows:
    - send_notification: {}
workflows:
  _finish:
    steps:
    - deploy-to-bitrise-io@2: {}
  _setup:
    steps:
    - pull-intermediate-files@1:
        inputs:
        - verbose: 'true'
    - script@1:
        inputs:
        - content: |-
            #!/usr/bin/env bash
            # fail if any commands fails
            set -e
            set -o pipefail
            set -x

            mv $TRANSPORTED_SOURCE_DIR $BITRISE_SOURCE_DIR/..
    - certificate-and-profile-installer@1: {}
    - recreate-user-schemes@1:
        inputs:
        - project_path: "$BITRISE_SOURCE_DIR/$BITRISE_PROJECT_PATH"
  build_iOS_16:
    before_run:
    - _setup
    after_run:
    - _finish
    steps:
    - xcode-archive@4:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
        - compile_bitcode: 'no'
        - upload_bitcode: 'no'
        - distribution_method: "$BITRISE_DISTRIBUTION_METHOD"
        - automatic_code_signing: apple-id
        - export_development_team: "$BITRISE_TEAM"
    envs:
    - SAMPLE_ENV_VAR: Test target A
  build_iOS_pre_16:
    before_run:
    - _setup
    after_run:
    - _finish
    steps:
    - xcode-archive@4:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
        - compile_bitcode: 'no'
        - upload_bitcode: 'no'
        - distribution_method: "$BITRISE_DISTRIBUTION_METHOD"
        - automatic_code_signing: apple-id
        - export_development_team: "$BITRISE_TEAM"
    envs:
    - SAMPLE_ENV_VAR: Test target B
    meta:
      bitrise.io:
        stack: osx-xcode-13.4.x
        machine_type_id: g2-m1.8core
  prepare:
    steps:
    - git-clone@8.0: {}
    - restore-cocoapods-cache@1: {}
    - certificate-and-profile-installer@1: {}
    - cocoapods-install: {}
    - save-cocoapods-cache@1: {}
    - deploy-to-bitrise-io@2:
        inputs:
        - pipeline_intermediate_files: "$BITRISE_SOURCE_DIR:TRANSPORTED_SOURCE_DIR"
  send_notification:
    steps:
    - script@1:
        inputs:
        - content: |-
            #!/usr/bin/env bash
            # fail if any commands fails
            set -e
            set -o pipefail
            set -x

            echo "Send notification 123"
    envs:
    - TARGET: Test target A
meta:
  bitrise.io:
    stack: osx-xcode-14.2.x-ventura
    machine_type_id: g2-m1.8core
app:
  envs:
  - opts:
      is_expand: false
    BITRISE_PROJECT_PATH: BitriseTest.xcworkspace
  - opts:
      is_expand: false
    BITRISE_SCHEME: BitriseTest
  - opts:
      is_expand: false
    BITRISE_DISTRIBUTION_METHOD: development
  - opts:
      is_expand: false
    BITRISE_TEAM: 72SA8V3WYL
  - opts:
      is_expand: false
    BITRISE_CODE_SIGNING_IDENTITY: Apple Development
trigger_map:
- tag: "*"
  pipeline: deploy_all